version: '3'

services:
  web:
    build: .docker/web
    container_name: web
    ports:
     - "8080:80"
     - "9000:9000"
    volumes:
     - .:/usr/share/nginx
     - .docker/web/nginx/conf:/etc/nginx/conf.d