<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="jumbotron w-100 p-5">
            <a href="/" class="text-decoration-none text-dark">
                <h1 class="display-4">Text Highlighter and Compiler</h1>
            </a>
            <p class="lead">Upload your code and take advantage of the highlighting and compilation features</p>
            <hr class="my-4">
            <div class="row">
                <?php if($this->view->fileName) { ?>
                    <h3 class="ml-3 font-weight-light"><?=$this->view->fileName?></h4>
                <?php } ?>
                <?php if($this->view->error) { ?>
                    <div class="alert alert-danger w-100 mx-3" role="alert">
                      <h4 class="alert-heading">Sorry,</h4>
                      <p><?=$this->view->error?> <?=$this->view->errorComplement?></p>
                    </div>
                <?php } ?>
                
                <?php if($this->view->highlighted) { ?>
                    <div class="container my-3">
                        <pre><code class="hljs <?=$this->view->highlighted->language?>"><?=$this->view->highlighted->value?></code></pre>
                    </div>                    
                <?php } ?>
            </div>
            <form id="main-form" method="post" enctype="multipart/form-data">
                <div class="row justify-content-between align-items-center">
                    <input type="hidden" name="fileName" value="<?=$this->view->fileName?>" />
                    <input type="hidden" name="code" value="<?=base64_encode($this->view->code)?>" />
                    <div class="form-group ml-3">
                        <input id="input-file" onchange="enableHighlight()" class="form-control-file" type="file" name="file">
                    </div>
                    <div class="row mr-3">
                        <input id="highlight-btn" class="btn btn-success mx-2" type="submit" disabled name="action" value="Highlight" />
                        <input class="btn btn-secondary" type="submit" <?= $this->view->code ? '' : 'disabled' ?> name="action" value="Compile" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>